import type { ResearchData, PlayerProfile } from "../../src/lib/research/types"
const token = "b".repeat(24),
  context = {
    token: "a".repeat(24),
    name: "Kickoff fixture",
    scoring: { rec: 1, rush_yd: 0.1 },
    positions: ["QB", "RB", "SUPER_FLEX"],
    teams: 12,
    dynasty: false,
  }
const player = {
  token,
  name: "Fixture Runner",
  position: "RB",
  team: "BUF",
  injury: null,
  adp: 40,
  held: 1,
  drafted: 1,
  updatedAt: "2026-09-10T12:00:00Z",
}
const acquisition = {
  key: "c".repeat(24),
  playerToken: token,
  name: player.name,
  position: "RB",
  team: "BUF",
  leagueToken: context.token,
  league: context.name,
  draftType: "auction",
  paid: 30,
  budget: 200,
  teams: 12,
  equivalentAdp: 52,
  marketAdp: 40,
  adpField: "adp_2qb" as const,
  adpGain: 12,
  impliedRank: 8,
  actualRank: 5,
  liveRank: 4,
  rankGain: 3,
  points: 20,
  livePoints: 32,
  games: 2,
  pointsAbovePrice: 4,
  peerDrafts: 3,
  matchedPlayers: 100,
  adjustedTeams: false,
  reason: null,
}
export const research: ResearchData = {
  season: 2026,
  week: 2,
  completedWeek: 1,
  fetchedAt: "2026-09-10T12:00:00Z",
  marketFetchedAt: "2026-09-10T12:00:00Z",
  marketUrl:
    "https://api.sleeper.app/projections/nfl/2026?season_type=regular&order_by=adp_ppr",
  statsFetchedAt: "2026-09-10T12:00:00Z",
  membershipCount: 4,
  completedDrafts: 2,
  snakeDrafts: 1,
  auctionDrafts: 1,
  unresolvedDrafts: 0,
  contexts: [context],
  players: [player],
  acquisitions: [acquisition],
  issues: [],
}
export const profile: PlayerProfile = {
  player,
  context,
  contexts: [context],
  acquisitions: [acquisition],
  adpField: "adp_2qb",
  marketAdp: 40,
  marketRank: 6,
  livePoints: 32,
  points: 20,
  ppg: 16,
  games: 2,
  actualRank: 5,
  liveRank: 4,
  eligiblePlayers: 30,
  weekly: [
    {
      week: 1,
      opponent: "SEA",
      points: 20,
      cumulative: 20,
      rank: 5,
      provisional: false,
      status: "Recorded",
      stats: { gp: 1, rec: 5, rush_yd: 150 },
    },
    {
      week: 2,
      opponent: "NE",
      points: 12,
      cumulative: 32,
      rank: 4,
      provisional: true,
      status: "Live / provisional",
      stats: { gp: 1, rec: 2, rush_yd: 100 },
    },
  ],
  season: 2026,
  completedWeek: 1,
  week: 2,
  marketFetchedAt: research.marketFetchedAt,
  statsFetchedAt: research.statsFetchedAt,
  issues: [],
}
